name: Testing Context Variables

on:
  workflow_dispatch:

env:
  CLOUD_PROVIDER: google-cloud

jobs:
  test_context_variables:
    runs-on: ubuntu-latest

    steps:
      - name: Check context variables
        run: |
          echo "Repository full name : ${{ github.repository }}"
          echo "Workflow name        : ${{ github.workflow }}"
          echo "Triggered by event   : ${{ github.event_name }}"
          echo "Branch name          : ${{ github.ref_name }}"
          echo "Commit SHA           : ${{ github.sha }}"
          echo "Actor                : ${{ github.actor }}"
          echo "Cloud provider       : $CLOUD_PROVIDER"