name: Testing Workflow Variables

on:
    workflow_dispatch

env:
    cloud: aws-cloud

jobs:
    greeting_job:
        runs-on: ubuntu-latest
        env:
            greeting: Hello
        steps:
            - name: Print Greeting
              run: echo "${{ env.greeting }}, welcome to the ${{ env.cloud }}!"
              env:
                first_name: Samarth